# Generated by Django 2.2 on 2020-01-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='country',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
