# Generated by Django 2.2 on 2020-01-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200104_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default=None, max_length=123),
        ),
        migrations.AddField(
            model_name='form',
            name='first_name',
            field=models.CharField(default=None, max_length=123),
        ),
        migrations.AddField(
            model_name='form',
            name='last_name',
            field=models.CharField(default=None, max_length=123),
        ),
        migrations.AddField(
            model_name='form',
            name='other_network',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='past_experience',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='payment_method',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='form',
            name='traffic_source',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='traffic_volume',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='vertical_type',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='where_here_about_advbuzz',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
