# Generated by Django 2.2 on 2020-01-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20200104_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='title',
        ),
        migrations.AddField(
            model_name='form',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='form',
            name='payment_method',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='form',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='where_here_about_advbuzz',
            field=models.CharField(max_length=500),
        ),
    ]
