# Generated by Django 2.2 on 2020-01-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20200104_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='other_network',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='past_experience',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='traffic_source',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='traffic_volume',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='vertical_type',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
