# Generated by Django 2.2 on 2020-01-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_auto_20200104_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='email',
        ),
        migrations.RemoveField(
            model_name='form',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='form',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='form',
            name='phone',
        ),
    ]
