# Generated by Django 2.2 on 2020-01-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_auto_20200104_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.EmailField(default=None, max_length=123),
        ),
        migrations.AddField(
            model_name='form',
            name='first_name',
            field=models.CharField(default=None, max_length=123),
        ),
        migrations.AddField(
            model_name='form',
            name='last_name',
            field=models.CharField(default=None, max_length=123),
        ),
        migrations.AddField(
            model_name='form',
            name='payment_method',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='form',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='form',
            name='where_here_about_advbuzz',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
