# Generated by Django 2.2 on 2020-03-17 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_auto_20200317_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='country',
        ),
    ]
